version: '3.3'

services:
  migration_control_web:
    image: migration_control
    container_name: migration_control_web
    build: .
    ports:
      - "4001:4001"
    command: sh -c "gunicorn migration_control_web.wsgi:application --bind 0.0.0.0:4001"
    restart: always
    env_file:
      - ./.env
    volumes:
      - .:/app/

  migration_control_redis:
    container_name: migration_control_redis
    image: "redis:alpine"

  migration_control_celery:
    container_name: migration_control_celery
    image: migration_control
    command: celery -A migration_control_web worker --pool solo
    volumes:
      - ./:/app/
    restart: always
    env_file:
      - ./.env
    depends_on:
      - migration_control_redis

  migration_control_celery_beat:
    build: .
    command: celery -A migration_control_web beat -l info
    volumes:
      - ./:/app/
    depends_on:
      - migration_control_redis