# Generated by Django 4.2.7 on 2026-06-04 07:28

from django.conf import settings
import django.contrib.auth.base_user
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import v1_1.common_utils.file_paths
import v1_1.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, default=None, max_length=28, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('surname', models.CharField(blank=True, max_length=150, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True)),
                ('avatar', models.ImageField(null=True, upload_to=v1_1.common_utils.file_paths.UploadPath('image'))),
                ('birthday', models.DateField(blank=True, null=True)),
                ('balance', models.FloatField(default=0)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('is_superuser', models.BooleanField(default=0, null=True)),
                ('is_active', models.BooleanField(default=1, null=True)),
                ('is_official', models.BooleanField(default=False, null=True)),
                ('pvc', models.CharField(blank=True, max_length=150, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            bases=(models.Model, django.contrib.auth.base_user.BaseUserManager),
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Выгода',
                'verbose_name_plural': 'Выгоды',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страну',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='DocumentsWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('passport', 'Паспорт'), ('migration_card', 'Миграционная карта'), ('registration', 'Регистрация'), ('patent', 'Патент'), ('paycheck', 'Чеки'), ('temporary_residence', 'Разрешение на временное проживание'), ('residence_permit', 'Вид на жительство'), ('certificate_asylum', 'Свидетельство о предоставлении временного убежища'), ('SNILS', 'СНИЛС'), ('INN', 'ИНН'), ('vmi_policy', 'Добровольное медицинское страхование')], max_length=50)),
                ('series', models.CharField(blank=True, max_length=30, null=True)),
                ('number', models.CharField(blank=True, max_length=30, null=True)),
                ('date_issue', models.DateField(blank=True, null=True)),
                ('issued_whom', models.CharField(blank=True, max_length=150, null=True)),
                ('territory_action', models.CharField(blank=True, max_length=150, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('archive', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizational_form', models.CharField(choices=[('1', 'ООО'), ('2', 'ПАО'), ('3', 'НАО'), ('4', 'ЗАО'), ('5', 'ИП')], default='1', max_length=1)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('inn', models.CharField(max_length=20, unique=True)),
                ('kpp', models.CharField(blank=True, max_length=9, null=True)),
                ('ogrn', models.CharField(blank=True, max_length=13, null=True)),
                ('okved', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=28, null=True, unique=True)),
                ('legal_address', models.CharField(blank=True, max_length=255)),
                ('actual_address', models.CharField(blank=True, max_length=255)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('user_agent', models.TextField()),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tariff', models.CharField(choices=[('standard', 'Стандартная'), ('pro', 'Про')], unique=True, verbose_name='Тип тарифа')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('number_organizations', models.IntegerField(default=1, verbose_name='Количество организаций')),
                ('number_workers', models.IntegerField(default=10, verbose_name='Количество работников')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('cost_organizations', models.FloatField(default=0, verbose_name='Цена за организацию')),
                ('cost_workers', models.FloatField(default=0, verbose_name='Цена за сотрудника')),
            ],
            options={
                'verbose_name': 'Тарифная ставка',
                'verbose_name_plural': 'Тарифные ставки',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='UserPvc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('pvc', models.CharField(default=v1_1.models.user.generate_pvc, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=50)),
                ('citizenship', models.CharField(blank=True, max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('place_birth', models.CharField(blank=True, max_length=255)),
                ('identification_card', models.CharField(choices=[('passport', 'Паспорт'), ('residence_permit', 'Вид на жительство'), ('certificate_asylum', 'Свидетельство о предоставлении убежища')], max_length=50)),
                ('date_employment', models.DateField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('actual_work_address', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('vacancy', 'Вакансия'), ('accepted', 'Принят'), ('dismissed', 'Уволен')], default='vacancy', max_length=50)),
                ('phone', models.CharField(blank=True, default=None, max_length=28, null=True)),
                ('registration_address', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('avatar', models.ImageField(null=True, upload_to=v1_1.common_utils.file_paths.UploadPath('image'))),
                ('processing_personal_data', models.BooleanField(default=0)),
                ('date_dismissal', models.DateField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('inn', models.CharField(blank=True, max_length=30, null=True)),
                ('snils', models.CharField(blank=True, max_length=30, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_1.organization')),
            ],
        ),
        migrations.CreateModel(
            name='UserOutstandingToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('device_id', models.IntegerField(choices=[[0, 'Desktop'], [1, 'Android'], [2, 'iOS'], [3, 'Mobile WEB'], [4, 'DWED infomat'], [5, 'TMED']], default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=128, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'token_blacklist_outstandingtoken',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('done', 'Выполнено'), ('overdue', 'Просрочено'), ('open', 'Открыто'), ('shifted', 'Сдвинуто'), ('cancelled', 'Отменено')], max_length=50)),
                ('days_until_expiration', models.CharField(max_length=30)),
                ('recommended_start_date', models.DateField()),
                ('document_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1_1.documentsworker')),
            ],
        ),
        migrations.CreateModel(
            name='TagsNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_1.news', verbose_name='Новость')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_1.tags', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег новости',
                'verbose_name_plural': 'Теги новости',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('process', 'В процессе'), ('active', 'Активная'), ('not_active', 'Не активная'), ('pause', 'Пауза')], default='process', max_length=50, verbose_name='Статус')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('service_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_1.servicerate', verbose_name='Тариф')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='ResponsiblePersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('surname', models.CharField(blank=True, max_length=150, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True)),
                ('passport_series', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_whom', models.CharField(max_length=150)),
                ('date_issue_passport', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_1.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MigrationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_1.organization')),
            ],
        ),
        migrations.CreateModel(
            name='HostPartyOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_host_party', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_host_party', models.CharField(blank=True, default=None, max_length=28, null=True, unique=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1_1.organization')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=255, verbose_name='Операция')),
                ('date_payment', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='FileDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_document', models.FileField(blank=True, null=True, upload_to=v1_1.common_utils.file_paths.UploadPath('documents'))),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_1.documentsworker')),
            ],
        ),
        migrations.AddField(
            model_name='documentsworker',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_1.worker'),
        ),
        migrations.CreateModel(
            name='DirectorOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_director', models.CharField(max_length=150)),
                ('surname_director', models.CharField(max_length=150)),
                ('patronymic_director', models.CharField(blank=True, max_length=150, null=True)),
                ('passport_series', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_whom', models.CharField(blank=True, max_length=150, null=True)),
                ('date_issue_passport', models.DateField(blank=True, null=True)),
                ('date_end_passport', models.DateField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1_1.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPersonOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=28, null=True)),
                ('additional_phone', models.CharField(blank=True, default=None, max_length=28, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1_1.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BookkeeperOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_bookkeeper', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1_1.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BodiesMIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_1.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bic', models.CharField(max_length=9, null=True)),
                ('name_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_account', models.CharField(max_length=20, null=True)),
                ('correspondent_account', models.CharField(max_length=20, null=True)),
                ('city_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1_1.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('type', models.CharField(choices=[('+', 'Пополнение'), ('-', 'Снятие')], max_length=20, verbose_name='Тип операции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Балансовый перевод',
                'verbose_name_plural': 'Балансовые переводы',
            },
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('observer', 'Зритель')], max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_1.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='BenefitsServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v1_1.benefits', verbose_name='Выгода')),
                ('service_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefitsservicerate_set', to='v1_1.servicerate', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Выгода тарифа',
                'verbose_name_plural': 'Выгоды тарифа',
                'unique_together': {('service_rate', 'benefit')},
            },
        ),
    ]
