# Generated by Django 4.2.7 on 2026-06-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerate',
            name='type_tariff',
            field=models.CharField(choices=[('basic', 'Базовая'), ('standard', 'Стандартная'), ('pro', 'Про')], unique=True, verbose_name='Тип тарифа'),
        ),
    ]
