# Generated by Django 4.2.7 on 2026-07-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_1', '0002_alter_servicerate_type_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='identification_card',
            field=models.CharField(choices=[('passport', 'Паспорт'), ('residence_permit', 'Вид на жительство'), ('certificate_asylum', 'Свидетельство о предоставлении временного убежища')], max_length=50),
        ),
    ]
